# Generated by Django 2.0.3 on 2018-04-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsdoit', '0003_auto_20180402_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='title',
            name='exp',
            field=models.IntegerField(),
        ),
    ]
