# Generated by Django 2.0.3 on 2018-04-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letsdoit', '0005_animals_birds_livings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='animals',
        ),
        migrations.DeleteModel(
            name='birds',
        ),
        migrations.DeleteModel(
            name='livings',
        ),
    ]
