# Generated by Django 2.0.3 on 2018-04-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsdoit', '0006_auto_20180403_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='livings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(blank=True, choices=[('a', 'animals'), ('b', 'birds')], max_length=1)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('legs', models.IntegerField()),
            ],
        ),
    ]
