# Generated by Django 2.0.3 on 2018-04-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsdoit', '0008_classyear_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='clasyear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1', 'Second year'), ('2', 'Thrird year'), ('3', 'Fourth year')], max_length=1)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
