# Generated by Django 2.0.3 on 2018-04-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsdoit', '0010_auto_20180403_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasyear',
            name='year',
            field=models.CharField(choices=[('Second year', '2'), ('Thrird year', '3'), ('Fourth year', '4')], max_length=10),
        ),
    ]
