# Generated by Django 2.0.3 on 2018-04-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsdoit', '0013_auto_20180403_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasyear',
            name='year',
            field=models.CharField(choices=[('2nd year', '2'), ('3rd year', '3'), ('4th year', '4')], max_length=100),
        ),
    ]
