# Generated by Django 2.0.3 on 2018-04-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letsdoit', '0016_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='filest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('fdescription', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='clasyear',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='filest',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letsdoit.clasyear', to_field='name'),
        ),
    ]
