# Generated by Django 2.0.3 on 2018-04-12 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letsdoit', '0017_auto_20180412_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='ftp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='files',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letsdoit.ftp'),
        ),
    ]
