# Generated by Django 2.0.3 on 2018-04-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letsdoit', '0018_auto_20180412_2144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='child',
        ),
        migrations.DeleteModel(
            name='classyear',
        ),
        migrations.RemoveField(
            model_name='files',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='livings',
        ),
        migrations.RemoveField(
            model_name='myinfo',
            name='myjob',
        ),
        migrations.DeleteModel(
            name='subjects',
        ),
        migrations.DeleteModel(
            name='title',
        ),
        migrations.DeleteModel(
            name='files',
        ),
        migrations.DeleteModel(
            name='ftp',
        ),
        migrations.DeleteModel(
            name='Myinfo',
        ),
        migrations.DeleteModel(
            name='Myjob',
        ),
    ]
