# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsdoit', '0019_auto_20180412_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filest',
            name='fname',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
