# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('letsdoit', '0020_auto_20180414_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filest',
            name='fname',
            field=models.FileField(blank=True, default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
