# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsdoit', '0023_auto_20180414_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='filest',
            name='usn',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
