# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsdoit', '0024_filest_usn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filest',
            name='usn',
            field=models.CharField(max_length=50),
        ),
    ]
