# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsdoit', '0025_auto_20180417_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasyear',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
