# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsdoit', '0026_auto_20180417_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
