# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsdoit', '0027_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='categorie',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
