# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsdoit', '0028_auto_20180417_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filest',
            name='fname',
            field=models.FileField(upload_to=''),
        ),
    ]
